#!/usr/bin/env python3
"""Generate symbol-based Ripes source and audit renderer test/CLI ELF files.
Requires GNU RISC-V tools only; does not run Ripes or repeat distance-11 gates.
"""
import argparse
import hashlib
import json
import re
import struct
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent.parent
OUT = ROOT / 'rv32/build/led'
sys.path.insert(0, str(HERE.parent))
from inspect_elf import inspect

PREFIX = 'riscv64-unknown-elf-'
CORE = ['rv32/start.S', 'rv32/asm_v5/parse.S', 'rv32/asm_v4/solve.S',
        'rv32/asm_v1/replay.S']
NEW = ['rv32/led/target.S', 'rv32/led/render.S']
TABLES = ['optimized/v1_tables.c', 'optimized_v2/v2_tables.c']
NAMES = ['v1_perm_next', 'v1_ori_next', 'v1_perm_dist',
         'v2_projection', 'v2_row_offset', 'v2_packed']
CASES = [('solved', '12345671111111', 0), ('short', '25314672313211', 1),
         ('distance11', '21345671111111', 11)]


def symbol_bytes(path):
    """Extract ELF32 object data symbols without a third-party dependency."""
    data = path.read_bytes()
    header = struct.unpack_from('<16sHHIIIIIHHHHHH', data)
    sections = [struct.unpack_from('<10I', data, header[6] + i*header[11])
                for i in range(header[12])]
    symbols = next(s for s in sections if s[1] == 2)
    strings = sections[symbols[6]]
    names = data[strings[4]:strings[4]+strings[5]]
    result = {}
    for off in range(symbols[4], symbols[4]+symbols[5], symbols[9]):
        name, value, size, info, other, index = struct.unpack_from('<IIIBBH', data, off)
        label = names[name:].split(b'\0', 1)[0].decode()
        if label in NAMES:
            sec = sections[index]
            start = sec[4]+value-sec[3]
            result[label] = data[start:start+size]
    return result


def split_source(source, renderer=False):
    parts = {'text': [], 'data': [], 'bss': []}
    mode = None
    # C-style block comments may span lines; strip them before directive routing.
    text = re.sub(r'/\*.*?\*/', '', source, flags=re.S)
    for line in text.splitlines():
        s = line.strip()
        if renderer and s in ('.if RENDER', '.endif'):
            continue
        if s.startswith('.section'):
            mode = 'text' if '.text.' in s else 'bss' if '.bss.' in s else 'data'
            continue
        if s.startswith(('.option', '.type', '.size')) or not s:
            continue
        if mode is None:
            raise ValueError('Unrouted source line: '+s)
        line = line.replace('.balign 4', '.align 2')
        if s.startswith('.word'):
            # Ripes tokenizes whitespace as an argument separator.
            line = re.sub(r'\s*\+\s*', '+', line)
        parts[mode].append(line)
    return parts


def source_for_ripes(state, expected, data_symbols, render, delay):
    parts = {'text': [], 'data': [], 'bss': []}
    for relative in CORE + NEW:
        conditional = relative.endswith('/render.S')
        routed = split_source((ROOT/relative).read_text(), conditional)
        for mode, lines in routed.items():
            if lines:
                parts[mode] += (['.if RENDER'] + lines + ['.endif']) if conditional else lines
    lines = ['# Generated by rv32/led/build.py. Core and tables come from asm-v5.',
             '# Instantiate LED Matrix 0 at Width=35 Height=25 before assembling RENDER=1.',
             f'.equ RENDER, {render}', f'.equ LED_DELAY, {delay}', '.text', *parts['text'],
             '.data', '.align 2', 'cube_input:', f'.asciz "{state}"', '.align 2',
             'expected_length:', f'.word {expected}']
    for name in NAMES:
        lines += ['.align 2', name+':']
        values = data_symbols[name]
        for i in range(0, len(values), 32):
            lines.append('.byte '+','.join(str(v) for v in values[i:i+32]))
    lines += parts['data']
    lines += ['.align 2', '__global_pointer$:', '__bss_start:', *parts['bss'],
              '.align 2', '__bss_zero_end:', '__stack_bottom:', '.zero 4096', '__stack_top:',
              '.byte 0']  # Ripes does not retain a trailing label without a following directive.
    # Ripes 5b8a616 accepts .equ and .zero, but not GNU .if/.endif or .space.
    # Resolve the shared source's assemble-time RENDER switch before loading it.
    enabled = [True]
    specialized = []
    for line in lines:
        directive = line.strip()
        if directive == '.if RENDER':
            enabled.append(enabled[-1] and bool(render))
        elif directive == '.endif':
            enabled.pop()
        elif enabled[-1]:
            specialized.append(line)
    assert len(enabled) == 1
    return '\n'.join(specialized)+'\n'


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument('--state')
    p.add_argument('--expected', type=int, default=-1)
    p.add_argument('--delay', type=int, default=300000,
                   help='Busy-loop iterations per frame; GUI visibility depends on simulation rate')
    args = p.parse_args()
    if not 0 <= args.delay <= 2147483647:
        p.error('--delay must be 0..2147483647')
    cases = CASES
    if args.state is not None:
        s = args.state
        if (len(s) != 14 or sorted(s[:7]) != list('1234567') or
                any(c not in '123' for c in s[7:]) or sum(int(c)-1 for c in s[7:]) % 3):
            p.error('Invalid cube input')
        if not -1 <= args.expected <= 11:
            p.error('--expected must be -1 or 0..11')
        cases = [('custom', s, args.expected)]
    elif args.expected != -1:
        p.error('--expected requires --state')
    OUT.mkdir(parents=True, exist_ok=True)
    commands = []
    def run(cmd):
        commands.append(cmd)
        subprocess.run(cmd, cwd=ROOT, check=True)
    # All historical files remain unchanged, checked against the gate's source commit.
    baseline = json.loads((ROOT/'rv32/asm_v5/baseline-files.json').read_text())
    for name, digest in baseline['sha256'].items():
        if hashlib.sha256((ROOT/name).read_bytes()).hexdigest() != digest:
            raise SystemExit('Historical source differs: '+name)
    objects, data_symbols = [], {}
    for source in TABLES:
        obj = OUT/(Path(source).stem+'.o')
        run([PREFIX+'gcc', '-O2', '-march=rv32i', '-mabi=ilp32', '-ffreestanding',
             '-ffunction-sections', '-fdata-sections', '-c', source, '-o', str(obj)])
        objects.append(str(obj))
        data_symbols.update(symbol_bytes(obj))
    assert set(data_symbols) == set(NAMES)
    summaries = []
    for render in (0, 1):
        assembly_objects = []
        config = OUT/f'config-{render}.S'
        # These MMIO constants exist ONLY in test ELF; GUI source uses Ripes symbols.
        config.write_text(f'.equ RENDER, {render}\n.equ LED_DELAY, 0\n'
                          '.equ LED_MATRIX_0_BASE, 0x200000\n'
                          '.equ LED_MATRIX_0_WIDTH, 35\n.equ LED_MATRIX_0_HEIGHT, 25\n')
        for relative in CORE + NEW:
            wrapper = OUT/(Path(relative).stem+f'-{render}.S')
            wrapper.write_text(config.read_text()+(ROOT/relative).read_text())
            obj = wrapper.with_suffix('.o')
            run([PREFIX+'gcc', '-march=rv32i', '-mabi=ilp32', '-c', str(wrapper), '-o', str(obj)])
            assembly_objects.append(str(obj))
        for label, state, expected in cases:
            input_s = OUT/(label+'-input.S')
            input_s.write_text('.section .rodata.input,"a",@progbits\n'
                               '.globl cube_input\ncube_input:\n'+f'.asciz "{state}"\n'
                               '.balign 4\n.globl expected_length\nexpected_length:\n'+f'.word {expected}\n')
            obj = input_s.with_suffix('.o')
            run([PREFIX+'gcc', '-march=rv32i', '-mabi=ilp32', '-c', str(input_s), '-o', str(obj)])
            variant = 'renderer-test' if render else 'cli'
            elf = OUT/f'{label}-{variant}.elf'
            run([PREFIX+'gcc', '-march=rv32i', '-mabi=ilp32', '-nostdlib',
                 '-Wl,--gc-sections', '-Wl,--build-id=none', '-Wl,-T,rv32/link.ld',
                 '-Wl,-Map,'+str(elf.with_suffix('.map')), *objects, *assembly_objects,
                 str(obj), '-o', str(elf)])
            audit = inspect(elf)
            summary = dict(case=label, input=state, expected_length=expected, renderer=bool(render),
                           test_mmio_base=0x200000 if render else None,
                           sha256=hashlib.sha256(elf.read_bytes()).hexdigest(), **audit)
            summaries.append(summary)
            name = f'{label}-'+('gui' if render else 'cli')+'.s'
            (OUT/name).write_text(source_for_ripes(state, expected, data_symbols, render, args.delay))
            print(f'{name}: .text={audit["text_bytes"]}, static={audit["static_data_bytes"]}')
    (OUT/'cases.json').write_text(json.dumps(summaries, indent=2)+'\n')
    paths = CORE+NEW+TABLES+['rv32/led/build.py', 'rv32/link.ld', 'rv32/inspect_elf.py']
    (OUT/'provenance.json').write_text(json.dumps(dict(
        source_commit=subprocess.check_output(['git','rev-parse','HEAD'],cwd=ROOT,text=True).strip(),
        renderer_delay=args.delay, historical_solver='asm-v5 at 4b5ec97',
        sha256={p:hashlib.sha256((ROOT/p).read_bytes()).hexdigest() for p in paths},
        commands=commands),indent=2)+'\n')
    print('LED_BUILD=PASS; GUI rendering and pinned Ripes still require local validation.')


if __name__ == '__main__':
    main()
