/* HOST program: derives every table from the original physical move model. */
#include "v1.h"
#include "host_reference.h"

static uint16_t tp[3 * V1_PERMS], to[3 * V1_ORIS];
static uint8_t dp[V1_PERMS], dor[V1_ORIS];
static uint16_t queue[V1_PERMS];

static int distances(unsigned n, const uint16_t *t, uint8_t *d)
{
    unsigned head = 0, tail = 1, maximum = 0;
    memset(d, 255, n);
    d[0] = 0;
    queue[0] = 0;
    while (head < tail) {
        unsigned here = queue[head++];
        for (unsigned face = 0; face < 3; ++face) {
            unsigned next = here;
            for (unsigned turn = 0; turn < 3; ++turn) {
                next = t[face * n + next];
                if (d[next] != 255)
                    continue;
                d[next] = (uint8_t)(d[here] + 1);
                if (d[next] > maximum)
                    maximum = d[next];
                if (tail >= n)
                    return 0;
                queue[tail++] = (uint16_t)next;
            }
        }
    }
    fprintf(stderr, "abstract states=%u visited=%u maximum=%u solved=%u\n",
            n, tail, maximum, d[0]);
    return tail == n && maximum <= V1_MAX_DEPTH;
}

static void emit_next(const char *name, unsigned n, const uint16_t *a)
{
    printf("const uint16_t %s[3][%u] = {\n", name, n);
    for (unsigned f = 0; f < 3; ++f) {
        puts("    {");
        for (unsigned i = 0; i < n; ++i) {
            if (i % 16 == 0) fputs("        ", stdout);
            printf("%u,", a[f * n + i]);
            if (i % 16 == 15 || i + 1 == n) putchar('\n');
        }
        puts("    },");
    }
    puts("};");
}

static void emit_dist(const char *name, unsigned n, const uint8_t *a)
{
    printf("const uint8_t %s[%u] = {\n", name, n);
    for (unsigned i = 0; i < n; ++i) {
        if (i % 32 == 0) fputs("    ", stdout);
        printf("%u,", a[i]);
        if (i % 32 == 31 || i + 1 == n) putchar('\n');
    }
    puts("};");
}

int main(void)
{
    state_t s;
    for (unsigned p = 0; p < V1_PERMS; ++p) {
        unrank_state(p * V1_ORIS, &s);
        for (unsigned f = 0; f < 3; ++f) {
            state_t next = quarter_turn(s, (uint8_t)f);
            tp[f * V1_PERMS + p] = (uint16_t)(rank_state(&next) / V1_ORIS);
        }
    }
    for (unsigned o = 0; o < V1_ORIS; ++o) {
        unrank_state(o, &s);
        for (unsigned f = 0; f < 3; ++f) {
            state_t next = quarter_turn(s, (uint8_t)f);
            to[f * V1_ORIS + o] = (uint16_t)(rank_state(&next) % V1_ORIS);
        }
    }
    if (!distances(V1_PERMS, tp, dp) ||
        !distances(V1_ORIS, to, dor))
        return 1;
    puts("/* Generated by generate_tables.c from baseline commit 308da1e. */");
    puts("#include \"v1.h\"");
    emit_next("v1_perm_next", V1_PERMS, tp);
    emit_next("v1_ori_next", V1_ORIS, to);
    emit_dist("v1_perm_dist", V1_PERMS, dp);
    emit_dist("v1_ori_dist", V1_ORIS, dor);
    return fflush(stdout) != 0 || ferror(stdout);
}
