#include "pattern_build.h"
/* The original CLI is never called; give this translation unit its own
 * symbol so host verification can include the same physical model too. */
#define baseline_cli_main pattern_build_unused_baseline_main
#include "../optimized/host_reference.h"
#undef baseline_cli_main

static unsigned placement_rank(unsigned a, unsigned b, unsigned c)
{
    return (a * 6 + b - (a < b)) * 5 + c - (a < c) - (b < c);
}

int host_build_pattern(host_pattern *pdb, const uint8_t cubies[3])
{
    if (!(cubies[0] < cubies[1] && cubies[1] < cubies[2] && cubies[2] < 7))
        return 0;
    for (unsigned k = 0; k < 3; ++k) pdb->cubies[k] = cubies[k];
    for (unsigned a = 0; a < 7; ++a)
        for (unsigned b = 0; b < 7; ++b) if (a != b)
            for (unsigned c = 0; c < 7; ++c) if (c != a && c != b) {
                unsigned q = placement_rank(a, b, c);
                pdb->positions[q][0] = (uint8_t)a;
                pdb->positions[q][1] = (uint8_t)b;
                pdb->positions[q][2] = (uint8_t)c;
                pdb->row_offset[q] = q * V2_ROW_BYTES;
            }
    for (unsigned f = 0; f < 3; ++f) {
        uint8_t destination[7];
        for (unsigned i = 0; i < 7; ++i) destination[source[f][i]] = (uint8_t)i;
        for (unsigned q = 0; q < V2_PLACEMENTS; ++q)
            pdb->next[f][q] = (uint8_t)placement_rank(
                destination[pdb->positions[q][0]],
                destination[pdb->positions[q][1]],
                destination[pdb->positions[q][2]]);
    }
    for (unsigned p = 0; p < V1_PERMS; ++p) {
        state_t state;
        uint8_t pos[3] = {0};
        unrank_state(p * V1_ORIS, &state);
        for (unsigned i = 0; i < 7; ++i)
            for (unsigned k = 0; k < 3; ++k)
                if (state.p[i] == cubies[k]) pos[k] = (uint8_t)i;
        pdb->projection[p] = (uint8_t)placement_rank(pos[0], pos[1], pos[2]);
    }
    pdb->goal_q = placement_rank(cubies[0], cubies[1], cubies[2]);
    uint32_t *queue = malloc((size_t)V2_ABSTRACT_STATES * sizeof *queue);
    if (!queue) return 0;
    memset(pdb->distance, 255, sizeof pdb->distance);
    unsigned head = 0, tail = 1, goal = pdb->goal_q * V1_ORIS;
    queue[0] = goal;
    pdb->distance[goal] = 0;
    pdb->maximum = 0;
    while (head < tail) {
        unsigned here = queue[head++], q = here / V1_ORIS, o = here % V1_ORIS;
        for (unsigned f = 0; f < 3; ++f) {
            unsigned nq = q, no = o;
            for (unsigned turn = 0; turn < 3; ++turn) {
                nq = pdb->next[f][nq];
                no = v1_ori_next[f][no];
                unsigned there = nq * V1_ORIS + no;
                if (pdb->distance[there] != 255) continue;
                unsigned d = pdb->distance[here] + 1U;
                if (tail >= V2_ABSTRACT_STATES || d > 11) {
                    free(queue);
                    return 0;
                }
                pdb->distance[there] = (uint8_t)d;
                if (d > pdb->maximum) pdb->maximum = d;
                queue[tail++] = there;
            }
        }
    }
    free(queue);
    if (tail != V2_ABSTRACT_STATES) return 0;
    /* Padding high nibbles at odd row ends remain sentinel 15. */
    memset(pdb->packed, 255, sizeof pdb->packed);
    for (unsigned q = 0; q < V2_PLACEMENTS; ++q)
        for (unsigned o = 0; o < V1_ORIS; ++o) {
            unsigned i = q * V2_ROW_BYTES + o / 2, shift = (o & 1U) * 4;
            unsigned mask = 15U << shift;
            pdb->packed[i] = (uint8_t)((pdb->packed[i] & ~mask) |
                                      (pdb->distance[q * V1_ORIS + o] << shift));
        }
    pdb->view = (v2_pattern){pdb->projection, pdb->row_offset, pdb->packed};
    return 1;
}

static void emit_bytes(const char *name, const uint8_t *a, unsigned n)
{
    printf("const uint8_t %s[%u] = {\n", name, n);
    for (unsigned i = 0; i < n; ++i) {
        if (i % 24 == 0) fputs("    ", stdout);
        printf("%u,", a[i]);
        if (i % 24 == 23 || i + 1 == n) putchar('\n');
    }
    puts("};");
}

int host_emit_pattern(const host_pattern *pdb)
{
    puts("/* Generated by the host C generator. See pattern.txt and results/pattern_sweep.csv. */");
    puts("#include \"v2.h\"");
    emit_bytes("v2_selected_cubies", pdb->cubies, 3);
    emit_bytes("v2_projection", pdb->projection, V1_PERMS);
    puts("const uint32_t v2_row_offset[210] = {");
    for (unsigned i = 0; i < V2_PLACEMENTS; ++i)
        printf("    %u,%s", pdb->row_offset[i], i % 8 == 7 || i == 209 ? "\n" : "");
    puts("};");
    emit_bytes("v2_packed", pdb->packed, V2_PACKED_BYTES);
    puts("const v2_pattern v2_default_pattern = {v2_projection, v2_row_offset, v2_packed};");
    return fflush(stdout) == 0 && !ferror(stdout);
}
